language: cpp
os: linux

notifications:
  email: false

cache:
  - apt
  - ccache

jobs:
    include:
        - os: linux
          name: "Linux Xenial with gcc 5.0 and Python3.6"
          dist: xenial
          compiler: gcc
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test', 'deadsnakes']
              packages: ['g++-5', 'ccache', 'libboost1.58-all-dev', 'cmake', 'cmake-data', 'python3.6-dev']
          env: [ CXX_COMPILER=g++-5, C_COMPILER=gcc-5, Z3_PKG=z3-4.8.9-x64-ubuntu-16.04, PYTHON_VERSION=3.6, PYTHON_INCLUDE_DIR=/usr/include/python3.6m, PYTHON_LIBRARY=/usr/lib/libpython3.6m.so, PYTHON_BINARY=/usr/bin/python3.6 ]

       
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-setuptools; fi
  - export CC="$C_COMPILER"
  - export CXX="$CXX_COMPILER"
  # Install pip
  - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
  - sudo ${PYTHON_BINARY} ./get-pip.py
  # Install z3
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.9/${Z3_PKG}.zip
  - unzip ${Z3_PKG}.zip
  # Back to /home/travis/build/JonathanSalwan
  - cd ..
  # Install gcov
  - if [[ "$GCOV" == "ON" ]]; then sudo ln -sf /usr/bin/gcov-5 /usr/bin/gcov; fi
  - if [[ "$GCOV" == "ON" ]]; then wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz; fi
  - if [[ "$GCOV" == "ON" ]]; then tar xf lcov_1.13.orig.tar.gz; fi
  - if [[ "$GCOV" == "ON" ]]; then sudo make -C lcov-1.13/ install; fi
  # Install capstone
  - wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
  - tar -xf ./4.0.2.tar.gz
  - cd ./capstone-4.0.2
  - bash ./make.sh
  - sudo make install
  - cd ../
  # Install unicorn. Only test AArch64 with Unicorn on Linux.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/unicorn-engine/unicorn; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ./unicorn; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git checkout ec4c6365c3c91703b3725540100023f6a03db742; fi # 1.0.2-rc2
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then UNICORN_ARCHS="x86 arm aarch64" ./make.sh; fi # we use unicorn to only test some semantics
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd bindings/python; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ${PYTHON_BINARY} ./setup.py install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../../../; fi
  # Install LIEF
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ${PYTHON_BINARY} -m pip install https://github.com/lief-project/LIEF/releases/download/0.7.0/linux_lief-0.7.0_py${PYTHON_VERSION}.tar.gz; fi
  # Download pin
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -U 'TritonBrowser/13.37 (X11; Linux x86_64; rv:31.337) Firefox/30.0' http://software.intel.com/sites/landingpage/pintool/downloads/pin-2.14-71313-gcc.4.4.7-linux.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xf pin-2.14-71313-gcc.4.4.7-linux.tar.gz; fi
  # Move Triton into pin
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv ./Triton ./pin-2.14-71313-gcc.4.4.7-linux/source/tools/; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ./pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton; fi

install:
  # Prepare build
  - mkdir build
  - cd build

script:
  # Install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DZ3_INCLUDE_DIRS=$PWD/../${Z3_PKG}/include -DZ3_LIBRARIES=$PWD/../${Z3_PKG}/bin/libz3.so -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DGCOV=${GCOV:OFF} -DPYTHON_VERSION=${PYTHON_VERSION} -DPINTOOL=${PINTOOL:OFF} -DKERNEL4=${KERNEL4:OFF} ..; fi
  - make -j2
  # Unittests
  # - travis_wait 60 make check
  # Check installation succeed
  - sudo make install

after_success:

