language: cpp
os: linux

notifications:
  email: false

cache:
  - apt
  - ccache

jobs:
    include:
        - os: linux
          name: "Linux Xenial with gcc 5.0 and Python3.7"
          dist: xenial
          compiler: gcc
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test', 'deadsnakes']
              packages: ['g++-5', 'ccache', 'libboost1.58-all-dev', 'cmake', 'cmake-data', 'python3.7-dev']
          env: [ CXX_COMPILER=g++-5, C_COMPILER=gcc-5, Z3_PKG=z3-4.8.10-x64-ubuntu-18.04, PYTHON_VERSION=3.7, PYTHON_INCLUDE_DIR=/usr/include/python3.7m, PYTHON_LIBRARY=/usr/lib/libpython3.7m.so, PYTHON_BINARY=/usr/bin/python3.7 ]

       
before_install:
  - sudo apt-get install python-setuptools
  - export CC="$C_COMPILER"
  - export CXX="$CXX_COMPILER"
  # Install pip
  - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
  - sudo ${PYTHON_BINARY} ./get-pip.py
  # Install z3
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/${Z3_PKG}.zip
  - unzip ${Z3_PKG}.zip
  # Back to /home/travis/build/JonathanSalwan
  - cd ..
  # Install capstone
  - wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
  - tar -xf ./4.0.2.tar.gz
  - cd ./capstone-4.0.2
  - bash ./make.sh
  - sudo make install
  - cd ../
  # Install unicorn. Only test AArch64 with Unicorn on Linux.
  - git clone https://github.com/unicorn-engine/unicorn
  - cd ./unicorn
  - git checkout ec4c6365c3c91703b3725540100023f6a03db742 # 1.0.2-rc2
  - UNICORN_ARCHS="x86 arm aarch64" ./make.sh # we use unicorn to only test some semantics
  -  sudo make install
  - cd bindings/python
  - sudo ${PYTHON_BINARY} ./setup.py install
  - cd ../../../
  # Install LIEF
  - sudo ${PYTHON_BINARY} -m pip install lief
  # Download pin
  - wget -U 'TritonBrowser/13.37 (X11; Linux x86_64; rv:31.337) Firefox/30.0' http://software.intel.com/sites/landingpage/pintool/downloads/pin-2.14-71313-gcc.4.4.7-linux.tar.gz
  - tar -xf pin-2.14-71313-gcc.4.4.7-linux.tar.gz
  # Move Triton into pin
  - mv ./Triton ./pin-2.14-71313-gcc.4.4.7-linux/source/tools/
  - cd ./pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton

install:
  # Prepare build
  - mkdir build
  - cd build

script:
  # Needs for unittests
  - sudo sh -c "echo 0 > /proc/sys/kernel/yama/ptrace_scope"
  # Install
  - cmake -DZ3_INCLUDE_DIRS=$PWD/../${Z3_PKG}/include -DZ3_LIBRARIES=$PWD/../${Z3_PKG}/bin/libz3.so -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DGCOV=${GCOV:OFF} -DPYTHON_VERSION=${PYTHON_VERSION} -DPINTOOL=${PINTOOL:ON} -DKERNEL4=${KERNEL4:OFF} ..
  - make -j2
  # Unittests
  # - travis_wait 60 make check
  # Check installation succeed
  - sudo make install
  # - zip -r triton.zip ./src/libtriton/*
  # - cp triton.zip /home/travis/build/nj00001
  -  ./src/examples/cpp/simplification
  

    
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "/home/travis/build/nj00001/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/build/src/libtriton/libtriton.so"
  skip_cleanup: true
  overwrite: true
  
